networks:
  logging_network:
    driver: bridge
    name: logging_network

volumes:
  mysql.data:
    name: mysql.data
  mongo.data:
    name: mongo.data
  elasticsearch.data:
    name: elasticsearch.data
  graylog.data:
    name: graylog.data

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    user: root
    ports:
      - 3308:3306
    env_file:
      - env.mysql
    command: --slow-query-log=1 --long-query-time=2 --slow-query-log-file=/var/log/mysql/mysql-slow.log
    networks:
      logging_network:
        aliases:
          - mysql.local
    volumes:
      - mysql.data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    networks:
      logging_network:
    depends_on:
      - elasticsearch

  filebeat_elasticsearch:
    container_name: filebeat_elasticsearch
    image: docker.elastic.co/beats/filebeat:7.14.2
    restart: always
    volumes:
      - ./filebeat_elastic.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./mysql/log/mysql-slow.log:/opt/mysql/log/mysql-slow.log:ro
    networks:
      logging_network:
    depends_on:
      - elasticsearch

  filebeat_graylog:
    container_name: filebeat_graylog
    image: docker.elastic.co/beats/filebeat:7.14.2
    restart: always
    volumes:
      - ./filebeat_graylog.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./mysql/log/mysql-slow.log:/opt/mysql/log/mysql-slow.log:ro
    networks:
      logging_network:
    depends_on:
      - graylog

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.14.2
    volumes:
      - elasticsearch.data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      discovery.type: single-node
    networks:
      logging_network:
        aliases:
          - elasticsearch.local

  kibana:
    image: kibana:7.14.2
    container_name: kibana
    restart: always
    ports:
      - 5602:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch.local:9200
    networks:
      logging_network:
        aliases:
          - kibana.local
    depends_on:
      - elasticsearch

  mongo:
    container_name: mongo
    image: mongo:latest
    networks:
      logging_network:
        aliases:
          - mongo.local
    ports:
      - 27017:27017
    volumes:
      - mongo.data:/data/db
      - mongo.data:/data/configdb
  
  graylog:
    image: graylog/graylog:4.2
    ports:
      - 9000:9000
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp
      - 5555:5555
    env_file:
      - env.graylog
    entrypoint: /usr/bin/tini -- wait-for-it  http://elasticsearch.local:9200 --  /docker-entrypoint.sh
    networks:
      logging_network:
        aliases:
          - graylog.local
    volumes:
      - graylog.data:/usr/share/graylog/data
    depends_on:
      - mongo
      - elasticsearch
